MIND-WALK/mindwalk_FE

package-lock.json, package.json, src/App.js
=> axios 설치, route 초기세팅

src/styles/ResetStyles.js
=> feat/initail-setting: 화면 width, height 세팅

src/styles/ResetStyles.js
- rem 설정
```
html {
font-size: 62.5%
}
```
사용할 때 16px일 경우 1.6rem으로 사용하시면 됩니다
- 메인, 서브 컬러 설정
```
div {
color: var(--main-green-color)
color: var(--sub-yellow-color)
}
```
전역변수 사용해서 컬러 사용해주세요
=> feat/initial-setting: rem 설정 및 메인 서브 컬러 설정

src/styles/ResetStyles.js
```
:root {
--main-green-color: #4DBA6D;  
--sub-green-color: #007D37;  
--sub-yellow-color: #F6EFAD;  
}
```
=> Feat/initail setting: 메인 컬러 설정

src/App.js, src/components/common/Btns/ClickBtnSm.jsx, src/components/common/Buttons/ClickButtonSm.jsx, src/components/common/Modal/ClickBottomModal.jsx
-  ClickButtonSm
-  ClickBottomModal
=> feat: 공통컴포넌트 생성 (ClickButtonSm,ClickBottomModal)

src/App.js
=> feat:App.js route 삭제

src/components/common/Modal/ClickBottomModal.jsx
=> ClickBottomModal 컴포넌트 style작업

src/App.js, src/styles/ResetStyles.js
- src>asset>img 폴더 추가
- font 적용오류 해결
=> 디렉토리 및 폰트 설정 추가

src/App.js, src/components/common/NavBar/index.jsx, src/constants/pathnameTitleMap.js
=> pathname별 navbar title 구현

.eslintrc.js, src/styles/ResetStyles.js
- 사용하지 않는 변수 에러 삭제
- 제한된 구문 경고 삭제
=> feat/initail-setting: eslint rule 추가

src/App.js, src/components/views/CompletedJourney/CompletedJourneyList.jsx, src/components/views/CompletedJourney/Journey.jsx, src/components/views/MyJourney/AchivementList.jsx, src/components/views/MyJourney/AchivementTracker.jsx, src/components/views/MyJourney/Level.jsx, src/constants/pathnameTitleMap.js, src/pages/CompletedJourney/index.jsx, src/pages/MyJourney/index.jsx
나의 여정 / 완수 여정 목록 페이지 UI 구현
- 이미지는 api 명세서 나온 후 삽입 예정
=> 나의 여정 / 완수 여정 목록 페이지 UI 구현

src/App.js, src/components/common/Buttons/ClickButtonBig.jsx, src/components/common/TabBar/index.jsx
=> Feat/common component@si

.env, .eslintrc.js, src/pages/Login/index.jsx
- login 시 /join API로 연결되어 아이디와 비밀번호 입력시 로그인 연결
- 로그인시 home 페이지로 이동
=> feat: login API 연결 구현

.eslintrc.js
=> feat: eslint 설정 추가-lf crlf오류 해결

src/App.js, src/pages/Challenge/ChallengeCompleted.jsx
=> feat/challenge 챌린지 완료 화면 구현

.eslintrc.js, src/App.js, src/apis/location.js, src/apis/weather.js, src/components/views/Main/Weather.jsx, src/hooks/queries/useLocation.jsx, src/hooks/queries/useWeather.jsx, src/hooks/useIcon.jsx, src/hooks/usePosition.jsx
- 위치 및 날씨 정보 로직 수정
- 사용자 위치 정보 시, 구 표출
=> Feat/main: 위치기반 날씨 정보 수정

src/pages/Challenge/ChallengeMap.jsx, src/pages/MyPage/Ask.jsx
- input 안에 간격 조절
- 챌린지 성공 alert 삭제
=> Feat/challenge map 챌린지맵 수정

src/components/common/TabBar/index.jsx
=> Feat/common component@sij2

src/pages/Challenge/ChallengeMap.jsx
=> 챌린지맵 console 삭제

src/components/views/MyPage/ProfileContainer.jsx
=> 마이페이지 프로필 사진 변경

src/components/common/CustomIcon/EmotionCard/AngryCard.jsx, src/components/common/CustomIcon/EmotionCard/HappyCard.jsx, src/components/common/CustomIcon/EmotionCard/NeutralCard.jsx, src/components/common/CustomIcon/EmotionCard/SadCard.jsx, src/components/common/CustomIcon/EmotionCard/SurprisedCard.jsx, src/components/common/Slide/index.jsx, src/pages/Analysis/index.jsx, src/pages/SelfDiagnosis/index.jsx
소요시간 NaN으로 뜸 | 자가진단에서 localestring 지움
=> Feat/self diagnosis@sij2

src/components/views/Challenge/ChallengeList.jsx, src/pages/Challenge/ChallengeMap.jsx
=> feat: ddp 주소 변경
